// Package config reads and validates autosolve inputs from environment variables.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
)

const (
	defaultCommitSignature = "Co-Authored-By: Claude <noreply@anthropic.com>"
	defaultBranchPrefix    = "autosolve/"
	defaultPRFooter        = "---\n\n*This PR was auto-generated by [claude-autosolve-action](https://github.com/cockroachdb/actions) using Claude Code.*\n*Please review carefully before approving.*"
)

// Config holds validated configuration for an autosolve run.
type Config struct {
	// Task inputs
	SystemPrompt       string
	Skill              string
	ContextVars        []string // env var names to pass through to Claude
	AssessmentCriteria string
	Model              string
	BlockedPaths       []string
	FooterType         string // "assessment" or "implementation"

	// Logging controls how much Claude output streams to the step log.
	//   "error" — errors and final status only (token counts, result)
	//   "info"  — result summary (turns, duration, cost) and permission denial warnings
	//   "debug" — all tool calls, assistant text, and tool I/O
	LogLevel string

	// ReadPaths are extra host paths to bind read-only into the sandbox.
	// Use for shared schemas, generated protos, or other references the
	// task needs to consult but not modify. Paths may be absolute or
	// relative to GITHUB_WORKSPACE.
	ReadPaths []string

	// ScratchDir is the per-run sandbox scratch dir at
	// $RUNNER_TEMP/autosolve-scratch (created by the action.yml setup
	// step). Bound read-write into the sandbox; HOME points to its
	// home/ subdir so claude session state persists across retries; the
	// commit-message and pr-body subpaths are where claude writes the
	// PR title/body coordination files.
	ScratchDir string

	// WorkingDir is the absolute path the binary runs in (set by the
	// action.yml `working-directory:` step setting). Bound read-write
	// into the sandbox and used as Claude's cwd. Must be a strict
	// subdirectory of GITHUB_WORKSPACE — never the workspace root, since
	// other actions (e.g. google-github-actions/auth) drop credential
	// files there.
	WorkingDir string

	// Implementation-specific
	MaxRetries   int
	AllowedTools string

	// PR creation
	ForkOwner       string
	ForkRepo        string
	ForkPushToken   string
	PRCreateToken   string
	PRBaseBranch    string
	PRLabels        string
	PRDraft         bool
	PRFooter        string
	GitUserName     string
	GitUserEmail    string
	BranchPrefix    string
	BranchSuffix    string
	CommitSignature string

	// GitHub context
	GithubRepository string
	PRTargetRepo     string // repo where PRs are created; defaults to GithubRepository
}

// LoadAssessConfig reads config for the assess subcommand.
func LoadAssessConfig() (*Config, error) {
	logLevel, err := parseLogLevel(os.Getenv("INPUT_LOG_LEVEL"))
	if err != nil {
		return nil, err
	}
	sandbox, err := loadSandboxConfig()
	if err != nil {
		return nil, err
	}
	c := &Config{
		SystemPrompt:       os.Getenv("INPUT_SYSTEM_PROMPT"),
		Skill:              os.Getenv("INPUT_SKILL"),
		ContextVars:        parseContextVars(os.Getenv("INPUT_CONTEXT_VARS")),
		AssessmentCriteria: os.Getenv("INPUT_ASSESSMENT_CRITERIA"),
		Model:              os.Getenv("INPUT_MODEL"),
		BlockedPaths:       ParseBlockedPaths(os.Getenv("INPUT_BLOCKED_PATHS")),
		FooterType:         "assessment",
		LogLevel:           logLevel,
		ReadPaths:          sandbox.readPaths,
		ScratchDir:         sandbox.scratchDir,
		WorkingDir:         sandbox.workingDir,

		GithubRepository: os.Getenv("GITHUB_REPOSITORY"),
	}
	if err := c.validateTask(); err != nil {
		return nil, err
	}
	return c, nil
}

// LoadImplementConfig reads config for the implement subcommand.
func LoadImplementConfig() (*Config, error) {
	prDraft, err := envBool("INPUT_PR_DRAFT", true)
	if err != nil {
		return nil, err
	}
	logLevel, err := parseLogLevel(os.Getenv("INPUT_LOG_LEVEL"))
	if err != nil {
		return nil, err
	}
	sandbox, err := loadSandboxConfig()
	if err != nil {
		return nil, err
	}

	c := &Config{
		SystemPrompt:    os.Getenv("INPUT_SYSTEM_PROMPT"),
		Skill:           os.Getenv("INPUT_SKILL"),
		ContextVars:     parseContextVars(os.Getenv("INPUT_CONTEXT_VARS")),
		Model:           os.Getenv("INPUT_MODEL"),
		BlockedPaths:    ParseBlockedPaths(os.Getenv("INPUT_BLOCKED_PATHS")),
		FooterType:      "implementation",
		LogLevel:        logLevel,
		ReadPaths:       sandbox.readPaths,
		ScratchDir:      sandbox.scratchDir,
		WorkingDir:      sandbox.workingDir,
		MaxRetries:      envOrDefaultInt("INPUT_MAX_RETRIES", 3),
		AllowedTools:    envOrDefault("INPUT_ALLOWED_TOOLS", "Read,Write,Edit,Grep,Glob,Bash(git add:*),Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git show:*),Bash(go build:*),Bash(go test:*),Bash(go vet:*),Bash(make:*)"),
		ForkOwner:       os.Getenv("INPUT_FORK_OWNER"),
		ForkRepo:        os.Getenv("INPUT_FORK_REPO"),
		ForkPushToken:   os.Getenv("INPUT_FORK_PUSH_TOKEN"),
		PRCreateToken:   os.Getenv("INPUT_PR_CREATE_TOKEN"),
		PRBaseBranch:    os.Getenv("INPUT_PR_BASE_BRANCH"),
		PRLabels:        envOrDefault("INPUT_PR_LABELS", "autosolve"),
		PRDraft:         prDraft,
		PRFooter:        envOrDefault("INPUT_PR_FOOTER", defaultPRFooter),
		GitUserName:     envOrDefault("INPUT_GIT_USER_NAME", "autosolve[bot]"),
		GitUserEmail:    envOrDefault("INPUT_GIT_USER_EMAIL", "autosolve[bot]@users.noreply.github.com"),
		BranchPrefix:    envOrDefault("INPUT_BRANCH_PREFIX", defaultBranchPrefix),
		BranchSuffix:    os.Getenv("INPUT_BRANCH_SUFFIX"),
		CommitSignature: envOrDefault("INPUT_COMMIT_SIGNATURE", defaultCommitSignature),

		GithubRepository: os.Getenv("GITHUB_REPOSITORY"),
		PRTargetRepo:     envOrDefault("INPUT_PR_TARGET_REPO", os.Getenv("GITHUB_REPOSITORY")),
	}
	if err := c.validateTask(); err != nil {
		return nil, err
	}
	if err := c.validatePR(); err != nil {
		return nil, err
	}

	// Remove tokens from the environment so they are not inherited by
	// child processes (e.g. Claude CLI). The values are already captured
	// in the Config struct.
	_ = os.Unsetenv("INPUT_FORK_PUSH_TOKEN")
	_ = os.Unsetenv("INPUT_PR_CREATE_TOKEN")

	return c, nil
}

func (c *Config) validateTask() error {
	if c.SystemPrompt == "" && c.Skill == "" {
		return fmt.Errorf("at least one of 'system_prompt' or 'skill' must be provided")
	}
	if c.Model == "" {
		return fmt.Errorf("'model' must be provided")
	}
	return nil
}

func (c *Config) validatePR() error {
	var missing []string
	if c.ForkOwner == "" {
		missing = append(missing, "fork_owner")
	}
	if c.ForkRepo == "" {
		missing = append(missing, "fork_repo")
	}
	if c.ForkPushToken == "" {
		missing = append(missing, "fork_push_token")
	}
	if c.PRCreateToken == "" {
		missing = append(missing, "pr_create_token")
	}
	if os.Getenv("SCRIPTS_DIR") == "" {
		missing = append(missing, "SCRIPTS_DIR")
	}
	if len(missing) > 0 {
		return fmt.Errorf("when create_pr is true, the following inputs are required: %s", strings.Join(missing, ", "))
	}
	return nil
}

// ValidateAuth checks that Vertex AI authentication is configured.
func ValidateAuth() error {
	if os.Getenv("CLAUDE_CODE_USE_VERTEX") != "1" {
		return fmt.Errorf("CLAUDE_CODE_USE_VERTEX must be set to '1'")
	}
	var missing []string
	if os.Getenv("ANTHROPIC_VERTEX_PROJECT_ID") == "" {
		missing = append(missing, "ANTHROPIC_VERTEX_PROJECT_ID")
	}
	if os.Getenv("CLOUD_ML_REGION") == "" {
		missing = append(missing, "CLOUD_ML_REGION")
	}
	if len(missing) > 0 {
		return fmt.Errorf("Vertex AI auth requires: %s", strings.Join(missing, ", "))
	}
	return nil
}

// requiredBlockedPaths are always blocked regardless of caller configuration.
// Workflow files must never be modifiable — they can run arbitrary code.
var requiredBlockedPaths = []string{".github/"}

// ParseBlockedPaths splits a comma-separated blocked paths string into a slice.
// The required paths are always included.
func ParseBlockedPaths(raw string) []string {
	paths := make(map[string]bool)
	for _, p := range requiredBlockedPaths {
		paths[p] = true
	}
	for _, p := range strings.Split(raw, ",") {
		p = strings.TrimSpace(p)
		if p != "" {
			paths[p] = true
		}
	}
	var result []string
	for _, p := range requiredBlockedPaths {
		result = append(result, p)
	}
	var extra []string
	for p := range paths {
		if !slices.Contains(requiredBlockedPaths, p) {
			extra = append(extra, p)
		}
	}
	sort.Strings(extra)
	return append(result, extra...)
}

// SecurityReviewModel returns a lightweight model suitable for the AI
// security review.
func (c *Config) SecurityReviewModel() string {
	return "claude-sonnet-4-6"
}

// sandboxInputs is the parsed/validated set of inputs that determine the
// bubblewrap bind layout. Loaded once per Config so both subcommands share
// the same validation rules.
type sandboxInputs struct {
	workingDir string   // absolute path; subdir of GITHUB_WORKSPACE
	scratchDir string   // absolute path; $RUNNER_TEMP/autosolve-scratch
	readPaths  []string // absolute paths; resolved against GITHUB_WORKSPACE
}

const scratchDirName = "autosolve-scratch"

// loadSandboxConfig validates the inputs that determine the sandbox bind
// layout. It enforces that the working directory is a strict subdirectory
// of GITHUB_WORKSPACE — never the workspace root, since other actions
// drop credential files there. Additional read paths are resolved against
// GITHUB_WORKSPACE if relative.
func loadSandboxConfig() (sandboxInputs, error) {
	var s sandboxInputs

	workspace := os.Getenv("GITHUB_WORKSPACE")
	if workspace == "" {
		return s, fmt.Errorf("GITHUB_WORKSPACE must be set")
	}
	absWorkspace, err := resolvePath(workspace)
	if err != nil {
		return s, fmt.Errorf("resolving GITHUB_WORKSPACE: %w", err)
	}

	cwd, err := os.Getwd()
	if err != nil {
		return s, fmt.Errorf("determining working directory: %w", err)
	}
	absCwd, err := resolvePath(cwd)
	if err != nil {
		return s, fmt.Errorf("resolving working directory: %w", err)
	}
	if absCwd == absWorkspace {
		return s, fmt.Errorf("working_directory must be a subdirectory of GITHUB_WORKSPACE, not the workspace root itself: check the target repo out into a subdirectory (e.g. ./repo) and set working_directory to that path")
	}
	if !strings.HasPrefix(absCwd, absWorkspace+string(filepath.Separator)) {
		return s, fmt.Errorf("working_directory %q must be a subdirectory of GITHUB_WORKSPACE %q", absCwd, absWorkspace)
	}
	s.workingDir = absCwd

	runnerTemp := os.Getenv("RUNNER_TEMP")
	if runnerTemp == "" {
		return s, fmt.Errorf("RUNNER_TEMP must be set")
	}
	absRunnerTemp, err := resolvePath(runnerTemp)
	if err != nil {
		return s, fmt.Errorf("resolving RUNNER_TEMP: %w", err)
	}
	s.scratchDir = filepath.Join(absRunnerTemp, scratchDirName)

	raw := os.Getenv("INPUT_READ_PATHS")
	for _, p := range strings.Split(raw, ",") {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		if !filepath.IsAbs(p) {
			p = filepath.Join(absWorkspace, p)
		}
		abs, err := resolvePath(p)
		if err != nil {
			return s, fmt.Errorf("resolving read_paths entry %q: %w", p, err)
		}
		s.readPaths = append(s.readPaths, abs)
	}

	// Auto-bind GOOGLE_APPLICATION_CREDENTIALS read-only when set, so the
	// in-sandbox Claude process can refresh Vertex tokens without the
	// caller having to list it in read_paths. With workload
	// identity federation the file is a federation config tied to
	// short-lived per-runner OIDC tokens, so the residual blast radius
	// is bounded.
	if creds := os.Getenv("GOOGLE_APPLICATION_CREDENTIALS"); creds != "" {
		abs, err := resolvePath(creds)
		if err != nil {
			return s, fmt.Errorf("resolving GOOGLE_APPLICATION_CREDENTIALS %q: %w", creds, err)
		}
		s.readPaths = append(s.readPaths, abs)
	}

	return s, nil
}

// resolvePath returns an absolute, symlink-resolved path. We use
// filepath.EvalSymlinks so that comparisons (e.g. cwd-under-workspace)
// work even when the caller passes one form of a symlinked path and we
// observe the other (commonly seen on macOS where /var → /private/var).
// EvalSymlinks requires the path to exist, which is fine for our inputs:
// GITHUB_WORKSPACE, RUNNER_TEMP, and read_paths must all
// exist for the bind mounts to work anyway.
func resolvePath(p string) (string, error) {
	abs, err := filepath.Abs(p)
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(abs)
	if err != nil {
		return "", err
	}
	return resolved, nil
}

func parseLogLevel(raw string) (string, error) {
	raw = strings.ToLower(strings.TrimSpace(raw))
	if raw == "" {
		return "error", nil
	}
	switch raw {
	case "error", "info", "debug":
		return raw, nil
	default:
		return "", fmt.Errorf("invalid log_level %q (expected error, info, or debug)", raw)
	}
}

func envBool(key string, def bool) (bool, error) {
	v := strings.ToLower(os.Getenv(key))
	if v == "" {
		return def, nil
	}
	switch v {
	case "true":
		return true, nil
	case "false":
		return false, nil
	default:
		return false, fmt.Errorf("invalid boolean value for %s: %q (expected true or false)", key, os.Getenv(key))
	}
}

func parseContextVars(raw string) []string {
	if raw == "" {
		return nil
	}
	var result []string
	for _, s := range strings.Split(raw, ",") {
		s = strings.TrimSpace(s)
		if s != "" {
			result = append(result, s)
		}
	}
	return result
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func envOrDefaultInt(key string, def int) int {
	v := os.Getenv(key)
	if v == "" {
		return def
	}
	n, err := strconv.Atoi(v)
	if err != nil {
		return def
	}
	return n
}
